# Generated by Django 4.2.26 on 2025-11-23 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='edad',
            field=models.CharField(max_length=50),
        ),
    ]
