# Generated by Django 5.2.6 on 2025-11-26 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='adoptada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mascota',
            name='adoptante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adopciones', to=settings.AUTH_USER_MODEL),
        ),
    ]
