# Generated by Django 4.2.26 on 2025-11-23 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0002_alter_mascota_edad'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='genero',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='mascota',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
